### PR TITLE
Remove net.ipv4.conf.*.secure_redirects = 0

### PR DESCRIPTION
**Pull request by TommyTran732**
This is redundant because `net.ipv4.conf.*.accept_redirects = 0` already takes care of it. If `net.ipv4.conf.*.accept_redirects = 1` and `net.ipv4.conf.*.secure_redirects = 0` then it will accept insecure redirects.

No point in having it.

### CODE REVIEW

**Comment by RoyalOughtness** [comment]
can you link the documentation that confirms this?

**Comment by TommyTran732** [comment]
Oh and I just asked Daniel (since GOS infra also doesn't have this setting). It's exactly what I thought this morning though.

**Comment by RoyalOughtness** [comment]
@TommyTran732 is there a doc link though?

**Comment by TommyTran732** [comment]
Nope, I can try to dig for it but eh

**Comment by RoyalOughtness** [comment]
I'd prefer to leave it unchanged/potentially redundant until we have confirmation that what we're changing has the effect we think it does

**Comment by thestinger** [comment]
@qoijjj It's disabling restricting redirects to secure redirects, not disabling accepting secure redirects separately from insecure ones. Check the Linux kernel sources. The code is straightforward, and nearly all online guides about this are wrong.

**Comment by thestinger** [comment]
There's a ton of misinformation about lots of Linux kernel sysctls, system calls, etc. The linux-man-pages project is not a reliable source of information as it has both outdated and inaccurate claims that were never true throughout, although it doesn't cover this.

**Comment by RoyalOughtness** [comment]
@thestinger Thanks, do you have a link to the code you're referring to? Would save me some time. If not, I'll look for it.

**Comment by thestinger** [comment]
Search for `IN_DEV_SEC_REDIRECTS`. The place it's used is in `net/ipv4/route.c`, `__ip_do_redirect`, and you can see there's a condition above handling whether redirects are enabled at all. It doesn't reach this unless redirects are enabled, it's not marked as shared media and then it only determines if it rejects an insecure redirect.

**Review by RoyalOughtness — DISMISSED** [review]

**Comment by RoyalOughtness** [comment]
@TommyTran732 please fix the conflicts then I'll merge

**Pull request merged**
