### PR TITLE
force sddm to use wayland instead of xorg

### PR DESCRIPTION
**Pull request by Sadoon-AlBader**
Given that the main focus is security I think this is a good idea :)

Straight from [Arch Wiki](https://wiki.archlinux.org/title/SDDM#Running_under_Wayland)

Also has the added benefit of making sddm look proper on a HiDPI monitor if the user sets the appropriate settings in KDE.

### CODE REVIEW

**Comment by RoyalOughtness** [comment]
This is great, thanks!

Can you add a comment clarifying what each of these flags is doing:

```
--drm --no-lockscreen --no-global-shortcuts --locale1
```

Also, please confirm that you've tested this configuration.

**Comment by Sadoon-AlBader** [comment]
> This is great, thanks!

No, thank *you* as I have been struggling with finding a reasonably secure Linux desktop :)
> Can you add a comment clarifying what each of these flags is doing:

Done.
> Also, please confirm that you've tested this configuration.

Tested and works well on two systems :D
One with an Intel iGPU and one with a clunky old Radeon card.

**Comment by RoyalOughtness** [comment]
One issue with this just occurred to me. This change will only work on the kinoite variants. Sericea also uses sddm, but doesn't include kwin, so this will cause breakage. Instead of adding this to a file, please add this to a script that echoes the contents of the file during image creation. you can then add a kinoite-scripts.yml and pull that in to all the kinoite images.

**Comment by Sadoon-AlBader** [comment]
> One issue with this just occurred to me. This change will only work on the kinoite variants. Sericea also uses sddm, but doesn't include kwin, so this will cause breakage.

Hmm I have an idea that will work with both. Need some time to test both though.

kwin $ARGS || sway $ARGS

Or possibly another way of doing this that is universal. Pretty sure it's doable.

**Comment by RoyalOughtness** [comment]
> > One issue with this just occurred to me. This change will only work on the kinoite variants. Sericea also uses sddm, but doesn't include kwin, so this will cause breakage.
> 
> Hmm I have an idea that will work with both. Need some time to test both though.
> 
> kwin $ARGS || sway $ARGS
> 
> Or possibly another way of doing this that is universal. Pretty sure it's doable.

I would think this would require different config for each variant. If there's a way to do it generically that would be good but I kind of doubt it since there are huge differences between different variants in terms of what packages are installed.

**Review by RoyalOughtness — CHANGES_REQUESTED** [review]
Need the change to be generic since other image variants use SDDM but may not have kwin

**Comment by RoyalOughtness** [comment]
@Sadoon-AlBader I was thinking about this and I think we can keep what you have as long as we move the file to a kinoite-specific directory. And then we can have kinoite-files.yml that gets ingested just in kinoite variants. That should solve the problem.

**Comment by RoyalOughtness** [comment]
completed: https://github.com/secureblue/secureblue/commit/02274d14ebe408964b82c41d3b54d91193d57e5b

**Pull request closed without merging**
