### PR TITLE
Add clamav

### PR DESCRIPTION
**Pull request by boredsquirrel**

### CODE REVIEW

**Comment by boredsquirrel** [comment]
#23

**Review by RoyalOughtness — CHANGES_REQUESTED** [review]
Please do not submit PRs until they are ready for review. You continue to have multiple commits in your PRs and unnecessary whitespace changes. You should not submit PRs until you have reviewed your changes in your branch yourself and tested them. I'll be adding documentation to clarify the requirements for PRs going forward.

**Comment by boredsquirrel** [comment]
sorry I dont know how to submit single PRs, they just stack on top of each other when I create them in Github.

The whitespaces are not by me, they are removed by me. I have no idea why they are there, but this gone after merging. I didnt actively remove anything, it was just like that and I dont really see adding random blanks or tabs to make it fit exactly

**Comment by RoyalOughtness** [comment]
> sorry I dont know how to submit single PRs, they just stack on top of each other when I create them in Github.

Please review the git documentation.

> The whitespaces are not by me, they are removed by me. I have no idea why they are there, but this gone after merging. I didnt actively remove anything, it was just like that and I dont really see adding random blanks or tabs to make it fit exactly

I am aware that the whitespaces are already there. Changes that modify whitespace unnecessarily will not be merged. Please remove those changes before submitting a pull request.

**Comment by boredsquirrel** [comment]
I will look into this. 

Okay let me elaborate: I opened the config files in my editor and that was the result, I didnt even touch these lines often. Adding random whitespaces is weird, my version has no extra whitespaces so it should be just fine

**Comment by RoyalOughtness** [comment]
> so it should be just fine

No, it is not fine. Please do not keep arguing about this.

**Comment by RoyalOughtness** [comment]
Apologies for the closure, I am rebasing the repo on top of startingpoint to get rid of the awful commit history. Better to do this now than after the project gains more traction

**Pull request closed without merging**
