### PR TITLE
DNS: add inactive insecure DNS configuation file

### PR DESCRIPTION
**Pull request by boredsquirrel**
this is a workaround, as currently no established solution exists. It has no tooling attached to it, but I would suggest a just command.

### CODE REVIEW

**Comment by boredsquirrel** [comment]
[One of the many discussions](https://discussion.fedoraproject.org/t/is-there-a-recommended-way-to-set-custom-dns-over-tls-https-servers-globally-that-will-not-break-captive-portal-logins)

Hopefully there will be a better way in the future, like launching a completely sandboxed process with split DNS.

As long as this is not there, I think adding such a "helper file" is useful. Just tried it on a train, and it works.

**Comment by RoyalOughtness** [comment]
Please explain what problem this solves and how. The existing settings are already set to opportunistic, meaning that if the nameserver provided over DHCP doesn't support DoT, it falls back. So this change should be completely unnecessary.

On top of that, having two drop ins that directly contradict each other is an anti-pattern.

**Comment by RoyalOughtness** [comment]
closing for the above reason.

**Comment by boredsquirrel** [comment]
that point makes sense and I will have to test this again, but I tried and it didnt work for me. After applying that setting it worked. I used Chromium and tried addressing a captive portal server both times.

opportunistic is not a good default tbh, it should be manually set to weak and otherwise users should know that their DNS is not tampered with.

I am not sure how the best structure for this would look like, but you can certainly place multiple config files in that directory and activate and deactivate them like this.

so to conclude
- the default setting made german ICE captive portal nonfunctional
- this config makes it work
- opportunistic as a workaround is not a secure solution and also doesnt work

**Comment by RoyalOughtness** [comment]
> not a good default

> not a secure solution

Can you explain why instead of just asserting it?

**Comment by RoyalOughtness** [comment]
Also, if you're having issues with a captive portal, it indicates there is a real problem here. It's just not clear at all why it would be an issue with the config and not an upstream issue with resolved. If opportunistic isn't falling back, then that's an upstream bug we've uncovered.

**Comment by boredsquirrel** [comment]
opportunistic is not a good default because the current config will use whatever DHCP offers, and if there is no encryption it will silently fall back to unencrypted, or am I wrong here?

Yes it seems so, I read something about resolved not handling that stupid insecure technology well (and I can't blame them).

I think captive portals are a mess, and we should not try to make them work by compromising the systems security. So I would enforce a secure DNS connection, request upstream to integrate a feature for example for split DNS to only allow a single process to use that insecure DNS, just for the captive portal login.

And in the meantime I personally use the added config, as my VPN app controls the DNS anyways. This is not a solution working for everyone, but afaik there is nothing better currently.

**Comment by RoyalOughtness** [comment]
> opportunistic is not a good default because the current config will use whatever DHCP offers, and if there is no encryption it will silently fall back to unencrypted, or am I wrong here?

You are correct, you just haven't elaborated why that's a bad thing. If anything, that should be solving your captive portal problem

> Yes it seems so, I read something about resolved not handling that stupid insecure technology well (and I can't blame them).

I have no idea what this means. My statement was about there being a bug in opportunistic DoT, not specific to captive portals. 


> afaik there is nothing better currently.

You still haven't elaborated what the problem is with opportunistic DoT. You keep reiterating that there's a problem, just asserting it but not explaining it. If DHCP offers DoT or the user configures a server that supports it, it will be used. Otherwise, it won't break. This seems optimal.

**Comment by boredsquirrel** [comment]
hm, to clear this up. Opportunistic, in this default configuration (which people will use because it is default) will use any DNS server advertised via DHCP. Then if that supports DoT it will use DoT, if not, then without any notice the DNS will be unencrypted and can be tampered with like in the core principle of Captive Portals.

So here is the error. Captive portals are the only exception, where you NEED this weak DNS setting. The system should not just "give up" if for example the DHCP Server is manipulated, or the network is compromised, and DoT doesnt work (on purpose or by accident). This is still the case when using captive portals, but here it is an active choice.

So the problem is that the system should not fall back to DoT, it should block instead. And in the specific scenario of captive portals, actively be insecure.

**Comment by RoyalOughtness** [comment]
> Then if that supports DoT it will use DoT, if not, then without any notice the DNS will be unencrypted

Correct. This seems entirely desirable. If users want to guarantee DoT, they can configure a DoT nameserver.

Breakage is not a notification system :)

> can be tampered with like in the core principle of Captive Portals.

Not sure what you're referring to. And even still, if captive portals are unusable without opportunistic DNS, all the more reason to keep it.

> Captive portals are the only exception

Incorrect. Users who don't want to configure a nameserver need it so they can use DHCP-provided DNS without DoT if it's not available.

> the DHCP Server is manipulated

Whether the server is manipulated or not has absolutely nothing to do with whether it's DoT. You're conflating concepts that have nothing to do with each other. An attacker manipulating your nameserver somehow can easily make their nameserver a DoT server.

> it should block instead

No, breakage isn't a notification system.

**Comment by boredsquirrel** [comment]
> Incorrect. Users who don't want to configure a nameserver need it so they can use DHCP-provided DNS without DoT if it's not available.

Why should secureblue allow to use unencrypted DNS? configs can still be overwritten if this would be a problem in some scenarios.

I think we can agree that neither silently switching to unencrypted DNS, nor having no internet without a notification is a good state.

> An attacker manipulating your nameserver somehow can easily make their nameserver a DoT server.

true of course. You would need to only allow certain public keys then, which may not be a feature in systemd-resolved.

So you are right, in this state forcing DoT will not really prevent such an attack. Still, in this current config, captive portals where broken for me. Maybe because the network wouldnt allow something insecure that it did allow when using encrypted DNS?

I dont know.

**Comment by RoyalOughtness** [comment]
> I think we can agree that neither silently switching to unencrypted DNS

I don't agree. As I already said above, if users want to guarantee DoT, they can configure a DoT nameserver.

> Still, in this current config, captive portals where broken for me. 

This is a real issue that needs to be fixed. We need to get to the bottom of why the captive portal isn't successfully downgrading, or if it's a different issue, then whatever that happens to be.

**Comment by boredsquirrel** [comment]
I will write a mail to my train sysadmins and hope for the best

**Pull request closed without merging**
