### PR TITLE
fix: dns-selector: correct set_browser_policy prompt to match code

### PR DESCRIPTION
**Pull request by spaceoden**
In the dns-selector, $set_browser_policy's prompt ("Would you like the resolver to be set in the default browser (hardened-chromium) via management policy? [Y/n] ") indicates that the default value is yes. Without this default value, pressing enter at the prompt (to accept the default) does not use the default setting of "y".

### CODE REVIEW

**Comment by RKNF404** [comment]
Oversight on my part, it should not imply the default is `y`. Users should opt-into that behavior.

**Comment by spaceoden** [comment]
Thanks for clarifying. I've updated the PR to correct the prompt to "[y/N]"

**Comment by RKNF404** [comment]
@spaceoden Thanks, this also made me realise the other expected defaults are not set either, like resolver_has_second_ip and resolver_supports_ipv6. They just need to be set to `"y"`, and set_browser_policy could instead be set to `"n"` for consistency. If you don't mind handling it.

**Comment by spaceoden** [comment]
@RKNF404 I added the default yes fix in #599 . Turns out setting the variable before taking input doesn't work because the input replaces its value even if the input is an empty string.

**Comment by RKNF404** [comment]
@spaceoden Saw that, thanks. Already approved it. With that, this PR also looks good.

**Review by RKNF404 — APPROVED** [review]

**Review by RoyalOughtness — APPROVED** [review]

**Pull request merged**
