### PR TITLE
Remove some opinionated changes from when this was a personal project

### LINKED ISSUE #25: Why is KDE-Partitionmanager replaced by gparted?
On the Kinoite spin this replacement is done. What is the reasoning for that? Its pretty odd

### LINKED ISSUE #26: fw updates / updates
> Also as I said it handles plasma extensions and firmware updates, so it is important.

Feel free to submit a PR adding back discover :)

> not included in automatic updates

my understanding is that both gnome-software and discover already automate this

> detection for metered connection (by default every connection is set to unmetered, so phone hotspot would be used!)
> detection of AC state
> detection of battery state at e.g. 50%

These would all be upstream and out of scope for this project.

> If this is not working, a GUI appstore is needed.

Again, please feel free to submit a PR to add it back

> I agree that an immutable system without layering might have advantages, even though I would not want to use it currently. 

It's not clear how this relates to the conversation.

### PR DESCRIPTION
**Pull request by RoyalOughtness**

### CODE REVIEW

**Comment by boredsquirrel** [comment]
appreciated. Plasma-notifier will be pretty unintrusive and can warn about firmware updates, as long as no fully automated solution is implemented.

It may warn about flatpak updates though, even though the autoupdate (they do, right? I think that is ublue default)

**Comment by RoyalOughtness** [comment]
> appreciated. Plasma-notifier will be pretty unintrusive and can warn about firmware updates, as long as no fully automated solution is implemented.
> 
> It may warn about flatpak updates though, even though the autoupdate (they do, right? I think that is ublue default)

I don't think it will, since flatpak won't be installed

**Comment by boredsquirrel** [comment]
now it seems that the rpm-ostree backend for Discover is removed? That would for sure remove unnecessary GUI popups while the updates are handled without the GUI in the Background.

**Comment by RoyalOughtness** [comment]
> now it seems that the rpm-ostree backend for Discover is removed? That would for sure remove unnecessary GUI popups while the updates are handled without the GUI in the Background.

I don't see anything related to that removed in the packages lists. Can you provide a screenshot of what you're expecting vs what you're seeing? 

>  That would for sure remove unnecessary GUI popups while the updates are handled without the GUI in the Background.

I have no idea what this means.

**Comment by boredsquirrel** [comment]
> I don't see anything related to that removed in the packages lists. Can you provide a screenshot of what you're expecting vs what you're seeing?

Also unsure, but Discover doesnt show the repos available for updates, and I could not find the package? Fresh install, maybe changed upstream?

Explanation: rpm-ostree updates are done fully automated, and not through any GUI. Needing a "yes I want an update" could be a security risk because people ignore that.

The problem lies upstream, that updates are not paused when no AC or battery low or metered Network, like they are in GrapheneOS for example.

But still, as GUI integration of rpm-ostree tells users they should layer packages (which is not the purpose of rpm-ostree) and slows down these stores drastically, its best to remove that backend. It is confusing by default, slows down the stores a lot and distracts from installing Flatpaks

**Comment by RoyalOughtness** [comment]
> Explanation: rpm-ostree updates are done fully automated, and not through any GUI. Needing a "yes I want an update" could be a security risk because people ignore that.

Having discover installed does not change this.

> The problem lies upstream, that updates are not paused when no AC or battery low or metered Network, like they are in GrapheneOS for example.

Please don't bump PRs or issues for upstream issues.

> But still, as GUI integration of rpm-ostree tells users they should layer packages

It does no such thing.

> (which is not the purpose of rpm-ostree) and slows down these stores drastically, its best to remove that backend. It is confusing by default, slows down the stores a lot and distracts from installing Flatpaks

If there is a real problem here, cut a new issue and provide evidence of the problem.

**Comment by boredsquirrel** [comment]
okay will do.

**Pull request merged**
