### PR TITLE
feat: add back pam-authramp

### PR DESCRIPTION
**Pull request by RoyalOughtness**

### CODE REVIEW

**Comment by RoyalOughtness** [comment]
thanks again @34N0 for all your hard work on this

**Comment by wandapeter** [comment]
:-)!

fyi the countdown setting will cause a bad SDDM user experience. i suggest only setting it to true for GDM!

**Comment by RoyalOughtness** [comment]
@34N0 good to know, thanks

So for SDDM, what is the expected experience like? Will SDDM prevent user input but with no message indicating when it will be unlocked?

**Comment by RoyalOughtness** [comment]
also @34N0, everything in the commented example is the default value, right?

**Comment by wandapeter** [comment]
> @34N0 good to know, thanks
> 
> So for SDDM, what is the expected experience like? Will SDDM prevent user input but with no message indicating when it will be unlocked?

i think it's simply failing the login. it's how SDDM handles PAM so it's actually the same with all PAM modules. so not an improvment over faillock but not worse.

**Comment by wandapeter** [comment]
> also @34N0, everything in the commented example is the default value, right?

yes

**Comment by RoyalOughtness** [comment]
@34N0 makes sense, this is going into staging after all so I'll check for myself :smile:

**Comment by RoyalOughtness** [comment]
@34N0 how does this look now? please approve once it looks good

**Comment by wandapeter** [comment]
> @34N0 how does this look now? please approve once it looks good

if you're open to different configurations for different display managers i would suggest setting countdown to true for GDM. I am looking forward to test this as well and maybe check different configurations.

**Comment by RoyalOughtness** [comment]
@34N0 I already added that in a script. Please have a look

**Pull request merged**
